### ISSUE TITLE
Needs update / rebuild for fractional VAT rates

### ISSUE THREAD

**Issue by jgullstr** [tuutti/php-paytrail-payment-api#12]
In [Paytrail's API](https://github.com/paytrail/api-documentation/blob/main/docs/paytrail-api.yaml), vatPercentage has been updated from int to float. This library still uses integers ([example](https://github.com/tuutti/php-paytrail-payment-api/blob/2.x/src/Model/Item.php)), which breaks fractional VAT rates.

**Comment by tuutti** [comment]
This should be fixed in 3.0.0 release. The new OpenAPI spec introduced some BC breaks so I had to bump the major version as well.
